In [1]:
import numpy as np
a= np.array([[2,3],[45]])
print a


SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a)? (<ipython-input-1-650927c655b5>, line 3)

In [2]:
import numpy as np
a= np.array([[2,3],[45]])
print (a)

[list([2, 3]) list([45])]


<ipython-input-2-f82e961d31f4>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a= np.array([[2,3],[45]])


In [3]:
import numpy as np
a= np.array([[2,3],[4,5]])
print (a)

[[2 3]
 [4 5]]


In [4]:
import numpy as np
a= np.array([[2,3],[4,5]])
print a

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a)? (<ipython-input-4-ddc17f1cb445>, line 3)

In [5]:
import numpy as np
a= np.array([1,2,3,4,5], ndmin=3)
print (a)

[[[1 2 3 4 5]]]


In [6]:
import numpy as np
a= np.array([1,2,3,4,5], ndmin=1)
print (a)

[1 2 3 4 5]


In [7]:
import numpy as np
a= np.array([1,2,3,4,5], ndmin=5)
print (a)

[[[[[1 2 3 4 5]]]]]


In [8]:
import numpy as np
a= np.array([1,2,3,4,5], dtype=complex)
print (a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [9]:
import numpy as np
import pandas as pd
a= np.array(['Kim','Ken','Ros','Ruth','Peter'])
s=pd.Series(data)
print (s)

NameError: name 'data' is not defined

In [10]:
import numpy as np
import pandas as pd
data= np.array(['Kim','Ken','Ros','Ruth','Peter'])
s=pd.Series(data)
print (s)

0      Kim
1      Ken
2      Ros
3     Ruth
4    Peter
dtype: object


In [11]:
import numpy as np
import pandas as pd
data= {'Name':['Kim','Ken','Ros','Ruth'],'Age':[23,28,54,14], 'Unit':['Eng','Kisw','Math','Bio']}
df=pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
s=pd.Series(data)
print (df)

ValueError: Shape of passed values is (5, 3), indices imply (4, 3)

In [12]:
import numpy as np
import pandas as pd
data= {'Name':['Kim','Ken','Ros','Ruth'],'Age':[23,28,54,14], 'Unit':['Eng','Kisw','Math','Bio']}
df=pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
s=pd.Series(data)
print (df)

       Name  Age  Unit
rank1   Kim   23   Eng
rank2   Ken   28  Kisw
rank3   Ros   54  Math
rank4  Ruth   14   Bio


In [13]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(5,3), index=['a','c','e','f','h'], columns=['one','two','three'])
df=df.reindex(['a','b','c','d','e','f','g','h',])
print (df)

        one       two     three
a -0.718950  0.537624  0.821348
b       NaN       NaN       NaN
c  1.435764  0.853104  1.123630
d       NaN       NaN       NaN
e -0.068736 -0.528137  1.014308
f -1.695793 -1.366791  0.552124
g       NaN       NaN       NaN
h  0.182686 -0.331039 -0.287509


In [14]:
 import numpy as np
import pandas as pd
data= {'Name':['Kim','Ken','Ros','Ruth'],'Age':[23,28,54,14], 'Unit':['Eng','Kisw','Math','Bio']}
df=pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
s=pd.Series(data)
print df['one'].isnull()

SyntaxError: invalid syntax (<ipython-input-14-176bbc5cb95f>, line 6)

In [15]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(5,3), index=['a','c','e','f','h'], columns=['one','two','three'])
df=df.reindex(['a','b','c','d','e','f','g','h',])
print df['one'].isnull()

SyntaxError: invalid syntax (<ipython-input-15-6185a81590e0>, line 5)

In [16]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(5,3), index=['a','c','e','f','h'], columns=['one','two','three'])
df=df.reindex(['a','b','c','d','e','f','g','h',])
b = df['one'],('a.notnull()', engine='python')
print (b)

SyntaxError: invalid syntax (<ipython-input-16-3858f96c3772>, line 5)

In [17]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(5,3), index=['a','c','e','f','h'], columns=['one','two','three'])
df=df.reindex(['a','b','c'])
print (df)
print ("NaN replaced by '0':")
print df.isnull(0)

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(df)? (<ipython-input-17-b269f6cbb048>, line 5)

In [18]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(5,3), index=['a','c','e','f','h'], columns=['one','two','three'])
df=df.reindex(['a','b','c'])
print (df)
print ("NaN replaced by '0':")
print df.isnull(0)

SyntaxError: invalid syntax (<ipython-input-18-70e628a52221>, line 7)

In [19]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(5,3), index=['a','c','e','f','h'], columns=['one','two','three'])
df=df.reindex(['a','b','c'])
print (df)
print ("NaN replaced by '0':")
print df.fillna(0)

SyntaxError: invalid syntax (<ipython-input-19-37df1bf9f784>, line 7)

In [20]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(5,3), index=['a','c','e','f','h'], columns=['one','two','three'])
df=df.reindex(['a','b','c'])
print (df)
print ("NaN replaced by '0':")


        one       two     three
a -1.659105 -0.057552 -1.284311
b       NaN       NaN       NaN
c  0.809937 -1.488936  2.280756
NaN replaced by '0':


In [21]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(5,3), index=['a','c','e','f','h'], columns=['one','two','three'])
df=df.reindex(['a','b','c','e','f','h'])
print df.fillna(method='pad')

SyntaxError: invalid syntax (<ipython-input-21-7b550ee67c2d>, line 5)

In [22]:
import pandas as pd
data = pd.read_csv('C/Downloads/business-operations-survey-2020-covid-19-csv.csv')
print(data)

FileNotFoundError: [Errno 2] No such file or directory: 'C/Downloads/business-operations-survey-2020-covid-19-csv.csv'

In [1]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/birthplace-2018-census-csv.csv')
print(data)

                                             description  \
0       Business status Alert Level 4: Fully operational   
1       Business status Alert Level 4: Fully operational   
2       Business status Alert Level 4: Fully operational   
3       Business status Alert Level 4: Fully operational   
4       Business status Alert Level 4: Fully operational   
...                                                  ...   
10053  Reasons why you expect COVID-19 pandemic to ch...   
10054  Reasons why you expect COVID-19 pandemic to ch...   
10055  Reasons why you expect COVID-19 pandemic to ch...   
10056  Reasons why you expect COVID-19 pandemic to ch...   
10057  Reasons why you expect COVID-19 pandemic to ch...   

                               industry  level             size line_code  \
0                                 total      0   6�19 employees  C0301.01   
1                                 total      0  20�49 employees  C0301.01   
2                                 total      0  

In [2]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/birthplace-2018-census-csv.csv')
print(data)

            Code                                    Birthplace  \
0           0001                                        At sea   
1           1000  Oceania and Antarctica (not further defined)   
2           1101                                     Australia   
3           1102                                Norfolk Island   
4           1199           Australian External Territories nec   
..           ...                                           ...   
273         9299                  Southern and East Africa nec   
274         0000                        Inadequately described   
275         9999                                    Not stated   
276  TotalStated                                  Total stated   
277        Total                                         Total   

     Census_night_population_count  Census_usually_resident_population_count  
0                               15                                        15  
1                                0               

In [3]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data)

   ID   NAME  SALARY  START_DATE        DEPT
0   1    Ken  254.45  01/01/2012         I.T
1   2   Mary  336.80  06/02/2014         H.R
2   3  Peter  456.50  12/12/2016     Finance
3   4   Rose  240.00  06/10/2010  Operations
4   5   Jeff  540.25  05/05/2015         I.T
5   6    Liz  360.30  16/12/2018     Finance
6   7    Joh  321.20  12/04/2014  Operations
7   8  Kelly  400.50  19/03/2019         I.T
8   9   Cate  289.55  20/10/2018         H.R
9  10  Bruce  380.45  16/04/2012     Finance


In [4]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/birthplace-2018-census-csv.csv')
print(data[0:6]['name'])

KeyError: 'name'

In [5]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/birthplace-2018-census-csv.csv')
print(data[0:8]['NAME'])

KeyError: 'NAME'

In [6]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data[0:8])

   Code                                    Birthplace  \
0  0001                                        At sea   
1  1000  Oceania and Antarctica (not further defined)   
2  1101                                     Australia   
3  1102                                Norfolk Island   
4  1199           Australian External Territories nec   
5  1201                                   New Zealand   
6  1300               Melanesia (not further defined)   
7  1301                                 New Caledonia   

   Census_night_population_count  Census_usually_resident_population_count  
0                             15                                        15  
1                              0                                         0  
2                          83622                                     75696  
3                            114                                       108  
4                              0                                         0  
5                       

In [7]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data[0:8])

   ID   NAME  SALARY  START_DATE        DEPT
0   1    Ken  254.45  01/01/2012         I.T
1   2   Mary  336.80  06/02/2014         H.R
2   3  Peter  456.50  12/12/2016     Finance
3   4   Rose  240.00  06/10/2010  Operations
4   5   Jeff  540.25  05/05/2015         I.T
5   6    Liz  360.30  16/12/2018     Finance
6   7    Joh  321.20  12/04/2014  Operations
7   8  Kelly  400.50  19/03/2019         I.T


In [8]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data[0:8]['salary'])

KeyError: 'salary'

In [9]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data.loc[:,['salary','name']])

KeyError: "None of [Index(['salary', 'name'], dtype='object')] are in the [columns]"

In [10]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data.loc[:,['SALARY','NAME']])

   SALARY   NAME
0  254.45    Ken
1  336.80   Mary
2  456.50  Peter
3  240.00   Rose
4  540.25   Jeff
5  360.30    Liz
6  321.20    Joh
7  400.50  Kelly
8  289.55   Cate
9  380.45  Bruce


In [11]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data.loc[[1,4,6,8,9],['salary','name']])

KeyError: "None of [Index(['salary', 'name'], dtype='object')] are in the [columns]"

In [12]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data.loc[[1,4,6,8,9],['SALARY','NAME']])

   SALARY   NAME
1  336.80   Mary
4  540.25   Jeff
6  321.20    Joh
8  289.55   Cate
9  380.45  Bruce


In [13]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data.loc[[2:9],['SALARY','NAME']])

SyntaxError: invalid syntax (<ipython-input-13-70cb9f982933>, line 3)

In [14]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data.loc[3:9,['SALARY','NAME']])

   SALARY   NAME
3  240.00   Rose
4  540.25   Jeff
5  360.30    Liz
6  321.20    Joh
7  400.50  Kelly
8  289.55   Cate
9  380.45  Bruce


In [15]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data.loc[3:9,['SALARY','NAME','DEPT']])

   SALARY   NAME        DEPT
3  240.00   Rose  Operations
4  540.25   Jeff         I.T
5  360.30    Liz     Finance
6  321.20    Joh  Operations
7  400.50  Kelly         I.T
8  289.55   Cate         H.R
9  380.45  Bruce     Finance


In [16]:
import pandas as pd
data = pd.read_csv('C:/Users/peter/Downloads/input.csv')
print(data.loc[3:5,['SALARY','NAME','DEPT']])

   SALARY  NAME        DEPT
3  240.00  Rose  Operations
4  540.25  Jeff         I.T
5  360.30   Liz     Finance
